### ISSUE TITLE
ag-grid-auto-complete converted for vue

### ISSUE THREAD

**Issue by myazarc** [superman-lopez/ag-grid-auto-complete#5]
Hi,
first of all thanks for this component. i convert this component for vue.

I published with your permission. If you want, you can add it to your repo. ([ag-grid-auto-complete-vue](https://github.com/myazarc/ag-grid-auto-complete-vue))

**Comment by superman-lopez** [comment]
Hi thanks for letting me know!  Glad it was of use to you.  I am not familiar with Vue, so I will need some time to have a look at your repo before adding it in mine.
