### ISSUE TITLE
After making a selection, how would you revert the value?

### ISSUE THREAD

**Issue by luke1629** [superman-lopez/ag-grid-auto-complete#6]
I'm making an api call after user selection. If the api call fails, how would I revert the cell to its original value?

**Comment by superman-lopez** [comment]
Hi, I am sorry for the late response: I realise only now that I don't get notifications for issues.

You could edit the component to catch the error in the subscription, and then close the editor (`this.params.api.stopEditing();`) while making sure `isCanceled` is set to `true`.
